### ISSUE TITLE
Depending API might have changed

### ISSUE THREAD

**Issue by wendehals** [useblocks/sphinx-needs-enterprise#43]
I'm trying to use sne for exporting needs from GitHub issues but fail because sne reports about missing API:

$ sne export sphinx-needs-basics-issues
Importing config from /workspaces/XXX/conf.py
Traceback (most recent call last):
  File "/usr/local/bin/sne", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sphinx_needs_enterprise/scripts/cli.py", line 91, in export_cmd
    service_obj, sphinx_config = service_loader(service, conf_path)
  File "/usr/local/lib/python3.8/dist-packages/sphinx_needs_enterprise/scripts/loader.py", line 38, in service_loader
    for name, provider in get_providers().items():
  File "/usr/local/lib/python3.8/dist-packages/sphinx_needs_enterprise/config.py", line 5, in get_providers
    from sphinx_needs_enterprise.services.jira import JiraService
  File "/usr/local/lib/python3.8/dist-packages/sphinx_needs_enterprise/services/jira.py", line 2, in <module>
    from m2r import convert as md_convert
  File "/usr/local/lib/python3.8/dist-packages/m2r.py", line 59, in <module>
    class RestBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'

I'm using a needs_services config like this:

needs_services = {
    'sphinx-needs-basics-issues': {
        'class': GithubService,
        'class_init': {
            'gh_type': 'issue'
        },
        'url': 'https://github.XXX.com/api/v3/repos/XXX/sphinx-needs-basics/issues?state=all',
        'username': os.environ.get('GITHUB_USERNAME', ''),
        'token': os.environ.get('GITHUB_TOKEN', ''),
        'download_avatars': False,
        'download_folder': 'company-avatars',
        'id_prefix': 'SPHINX_NEEDS_BASICS_ISSUE_'
    }
}

**Comment by wendehals** [comment]
This is the version of m2r:

pip install --upgrade m2r
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: m2r in /usr/local/lib/python3.8/dist-packages (0.2.1)
Requirement already satisfied: docutils in /usr/local/lib/python3.8/dist-packages (from m2r) (0.17.1)
Requirement already satisfied: mistune in /usr/local/lib/python3.8/dist-packages (from m2r) (2.0.2)

**Comment by danwos** [comment]
Moving on to https://github.com/crossnox/m2r2 may solve the problem, which is a compatible fork, as m2r seems not to be maintained anymore.

@wendehals: Thanks for this hint :+1:
